import express from 'express';import{createServer}from'http';import{Server}from'socket.io';import path from'path';import{fileURLToPath}from'url';
const app=express(),http=createServer(app),io=new Server(http,{cors:{origin:'*'}}),rooms=new Map();
const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const deck=()=>{let d=suits.flatMap(s=>ranks.map(r=>({r,s})));for(let i=d.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d};
const score=h=>{let n=0,a=0;for(const c of h){if(c.r==='A'){n+=11;a++}else n+=['J','Q','K'].includes(c.r)?10:+c.r}while(n>21&&a){n-=10;a--}return n};
const code=()=>Math.random().toString(36).slice(2,7).toUpperCase();
const publicRoom=r=>({...r,deck:undefined,players:r.players.map(p=>({...p,sid:undefined}))});
const emit=r=>io.to(r.code).emit('room',publicRoom(r));
function finish(r){const dealer=r.players.find(p=>p.id===r.dealerId),ds=score(dealer.hand);r.players.filter(p=>p.id!==r.dealerId).forEach(p=>{let ps=score(p.hand),delta=0,label='แพ้';if(ps>21)delta=-p.bet;else if(ps===21&&p.hand.length===2&&!(ds===21&&dealer.hand.length===2)){delta=p.bet*1.5;label='Blackjack'}else if(ds>21||ps>ds){delta=p.bet;label='ชนะ'}else if(ps===ds){delta=0;label='เสมอ'}else delta=-p.bet;p.balance+=delta;dealer.balance-=delta;p.result={label,delta};});dealer.result={label:dealer.balance>=0?'เจ้ามือรับ':'เจ้ามือจ่าย',delta:0};r.phase='result';r.message='จบขาแล้ว';r.history.unshift({round:r.round,at:Date.now(),dealer:dealer.name,results:r.players.filter(p=>p.id!==dealer.id).map(p=>({name:p.name,delta:p.result.delta}))});emit(r)}
function next(r){let i=r.turn+1;while(i<r.order.length&&r.players.find(p=>p.id===r.order[i])?.done)i++;if(i<r.order.length){r.turn=i;r.message=`ตาของ ${r.players.find(p=>p.id===r.order[i]).name}`}else{let d=r.players.find(p=>p.id===r.dealerId);r.turn=r.order.length;r.message=`ตาเจ้ามือ ${d.name}`;if(score(d.hand)>=17){d.done=true;finish(r)}}emit(r)}
io.on('connection',s=>{s.on('create',({name},cb)=>{let c;do c=code();while(rooms.has(c));let p={id:crypto.randomUUID(),sid:s.id,name:String(name||'ผู้เล่น').slice(0,25),role:'player',bet:10,balance:0,hand:[],done:false};let r={code:c,hostId:p.id,dealerId:null,phase:'lobby',round:0,players:[p],deck:[],order:[],turn:0,message:'เลือกเจ้ามือและวางเดิมพัน',history:[]};rooms.set(c,r);s.join(c);s.data={code:c,id:p.id};emit(r);cb({ok:true,id:p.id,code:c})});
s.on('join',({code:c,name},cb)=>{let r=rooms.get(String(c).toUpperCase());if(!r)return cb({ok:false,error:'ไม่พบห้อง'});if(r.phase==='playing')return cb({ok:false,error:'กำลังเล่นอยู่ กรุณารอจบขา'});if(r.players.length>=8)return cb({ok:false,error:'ห้องเต็ม'});let p={id:crypto.randomUUID(),sid:s.id,name:String(name||'ผู้เล่น').slice(0,25),role:'player',bet:10,balance:0,hand:[],done:false};r.players.push(p);s.join(r.code);s.data={code:r.code,id:p.id};emit(r);cb({ok:true,id:p.id,code:r.code})});
s.on('action',(a,cb=()=>{})=>{let r=rooms.get(s.data?.code),p=r?.players.find(x=>x.id===s.data?.id);if(!r||!p)return cb({ok:false,error:'ไม่พบห้อง'});let fail=e=>cb({ok:false,error:e});
if(a.type==='dealer'){if(r.phase==='playing')return fail('เปลี่ยนเจ้ามือระหว่างขาไม่ได้');r.dealerId=p.id;r.players.forEach(x=>x.role=x.id===p.id?'dealer':'player');r.message=`${p.name} เป็นเจ้ามือ`;emit(r)}
else if(a.type==='bet'){let n=Math.floor(+a.value);if(r.phase==='playing'||p.id===r.dealerId)return fail('วางเดิมพันไม่ได้');if(n<10||n>500)return fail('เดิมพันต้องอยู่ระหว่าง 10–500');p.bet=n;emit(r)}
else if(a.type==='start'){if(!r.dealerId)return fail('กรุณาเลือกเจ้ามือ');if(!['lobby','result'].includes(r.phase))return fail('เกมเริ่มแล้ว');if(p.id!==r.hostId&&p.id!==r.dealerId)return fail('เจ้าห้องหรือเจ้ามือเท่านั้นที่เริ่มได้');r.deck=deck();r.round++;r.phase='playing';r.players.forEach(x=>{x.hand=[r.deck.pop(),r.deck.pop()];x.done=false;x.result=null});r.order=r.players.filter(x=>x.id!==r.dealerId).map(x=>x.id);r.turn=0;r.message=`ตาของ ${r.players.find(x=>x.id===r.order[0])?.name||'เจ้ามือ'}`;if(!r.order.length)finish(r);else emit(r)}
else if(['hit','stand','double'].includes(a.type)){let current=r.turn<r.order.length?r.order[r.turn]:r.dealerId;if(p.id!==current)return fail('ยังไม่ถึงตาของคุณ');let sc=score(p.hand);if(a.type==='hit'){if(p.id===r.dealerId&&sc>=17)return fail('เจ้ามือต้องหยุดเมื่อแต้มตั้งแต่ 17');p.hand.push(r.deck.pop());if(score(p.hand)>=21){p.done=true;p.id===r.dealerId?finish(r):next(r)}else emit(r)}else if(a.type==='stand'){if(p.id===r.dealerId&&sc<17)return fail('เจ้ามือต้องจั่วจนถึง 17');p.done=true;p.id===r.dealerId?finish(r):next(r)}else{if(p.id===r.dealerId||p.hand.length!==2||p.bet*2>1000)return fail('Double ไม่ได้');p.bet*=2;p.hand.push(r.deck.pop());p.done=true;next(r)}}
else if(a.type==='reset'){if(r.phase!=='result')return fail('ยังไม่จบขา');r.phase='lobby';r.players.forEach(x=>{x.hand=[];x.done=false;x.result=null});r.message='เลือกเจ้ามือ วางเดิมพัน แล้วเริ่มขาใหม่';emit(r)}cb({ok:true})});
s.on('disconnect',()=>{let r=rooms.get(s.data?.code);if(!r)return;let p=r.players.find(x=>x.id===s.data.id);if(p)p.offline=true;emit(r)})});
const root=path.dirname(fileURLToPath(import.meta.url));app.use(express.static(path.join(root,'dist')));app.use((q,res)=>res.sendFile(path.join(root,'dist/index.html')));http.listen(process.env.PORT||3001,()=>console.log('Blackjack server ready'));
